/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Calculo.EnergiaCombustivelFossil;
import javax.swing.JOptionPane;

/**
 *
 * @author davic
 */
public class CalcuCombustivelFossil extends javax.swing.JFrame {

    /**
     * Creates new form CalcuCombustivelFossil
     */
    public CalcuCombustivelFossil() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        cboxCombustivel = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtVolume = new javax.swing.JTextField();
        txtResultado = new javax.swing.JTextField();
        btnRegistroCombus = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel2.setText("Cálculo de Energia Combústivel Fóssil\n");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, -1, -1));

        cboxCombustivel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        cboxCombustivel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gás Natural", "Diesel", "hvo", " ", " ", " ", " " }));
        cboxCombustivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxCombustivelActionPerformed(evt);
            }
        });
        getContentPane().add(cboxCombustivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setText("Volume: ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, -1, -1));

        txtVolume.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        getContentPane().add(txtVolume, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 370, 110, -1));
        getContentPane().add(txtResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 450, 110, 30));

        btnRegistroCombus.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnRegistroCombus.setText("Confirmar Valores");
        btnRegistroCombus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroCombusActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistroCombus, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 500, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Imagens/fundo.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 900, 460));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Imagens/Consulta.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1080, 1070));

        jMenu1.setText("Energias");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Menu de Energias");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Relatório");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboxCombustivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxCombustivelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboxCombustivelActionPerformed

    private void btnRegistroCombusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroCombusActionPerformed

        try {
        double volume = Double.parseDouble(txtVolume.getText());

        String tipoCombustivel = cboxCombustivel.getSelectedItem().toString().toLowerCase();

        double poderCalorifico;
        double transformidade;

        switch (tipoCombustivel) {
            case "diesel":
                poderCalorifico = 36.55;
                transformidade = 6.6e4;
                break;
            case "gás natural":
                poderCalorifico = 36.66;
                transformidade = 4.8e4;
                break;
            case "hvo":
                poderCalorifico = 34.32;
                transformidade = 1.24e5;
                break;
            default:
                throw new IllegalArgumentException("Tipo de combustível inválido.");
        }

        EnergiaCombustivelFossil combustivel = new EnergiaCombustivelFossil(volume, poderCalorifico, tipoCombustivel);

        double emergia = combustivel.calcularEmergiaTotal();

        txtResultado.setText(String.format("%.2e sej", emergia));

    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "Por favor, insira um número válido para o volume.");
    } catch (IllegalArgumentException ex) {
        JOptionPane.showMessageDialog(this, ex.getMessage());
    }

    }//GEN-LAST:event_btnRegistroCombusActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed

    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        Consulta con = new Consulta();
        con.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalcuCombustivelFossil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalcuCombustivelFossil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalcuCombustivelFossil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalcuCombustivelFossil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalcuCombustivelFossil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistroCombus;
    private javax.swing.JComboBox<String> cboxCombustivel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JTextField txtResultado;
    private javax.swing.JTextField txtVolume;
    // End of variables declaration//GEN-END:variables
}
