/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author davic
 */
public class Consulta extends javax.swing.JFrame {

    /**
     * Creates new form Consulta
     */
    public Consulta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtQtdDispositivo = new javax.swing.JTextField();
        txtPtDispositvo = new javax.swing.JTextField();
        txtHrsUso = new javax.swing.JTextField();
        btnAd = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        lblPtDispositivo = new javax.swing.JLabel();
        lblHrsUso = new javax.swing.JLabel();
        lblqtdDispositivo = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        lblQuadroBranco = new javax.swing.JLabel();
        lblPlanoFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtQtdDispositivo.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        getContentPane().add(txtQtdDispositivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 340, 150, -1));

        txtPtDispositvo.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        getContentPane().add(txtPtDispositvo, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 390, 150, -1));

        txtHrsUso.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtHrsUso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHrsUsoActionPerformed(evt);
            }
        });
        getContentPane().add(txtHrsUso, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 440, 150, -1));

        btnAd.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnAd.setText("Confirmar Dispositivo");
        getContentPane().add(btnAd, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 550, -1, -1));

        jButton1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton1.setText("Relatório");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 610, -1, -1));

        lblPtDispositivo.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblPtDispositivo.setText("Potência de cada dispositivo:");
        getContentPane().add(lblPtDispositivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 390, -1, -1));

        lblHrsUso.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblHrsUso.setText("Tempo médio em horas do dispositivo em uso:");
        getContentPane().add(lblHrsUso, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 440, -1, -1));

        lblqtdDispositivo.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblqtdDispositivo.setText("Quantidade do dispositivo:");
        getContentPane().add(lblqtdDispositivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, -1, -1));

        lblTitulo.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        lblTitulo.setText("Cálculo do Consumo de Energia Elétrica");
        getContentPane().add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, -1, -1));

        jButton2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton2.setText("Dispositivos");
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 610, -1, -1));

        lblQuadroBranco.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblQuadroBranco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Imagens/Painel Branco.jpg"))); // NOI18N
        lblQuadroBranco.setText("jLabel3");
        getContentPane().add(lblQuadroBranco, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 890, 410));

        lblPlanoFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Imagens/Consulta.png"))); // NOI18N
        getContentPane().add(lblPlanoFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1200, 1090));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtHrsUsoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHrsUsoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHrsUsoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Consulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Consulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Consulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Consulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Consulta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAd;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel lblHrsUso;
    private javax.swing.JLabel lblPlanoFundo;
    private javax.swing.JLabel lblPtDispositivo;
    private javax.swing.JLabel lblQuadroBranco;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblqtdDispositivo;
    private javax.swing.JTextField txtHrsUso;
    private javax.swing.JTextField txtPtDispositvo;
    private javax.swing.JTextField txtQtdDispositivo;
    // End of variables declaration//GEN-END:variables
}
