/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author davic
 */
public class EscolhaDispositivoEnEletrica extends javax.swing.JFrame {

    /**
     * Creates new form EscolhaDispositivoEnEletrica
     */
    public EscolhaDispositivoEnEletrica() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTiTulo = new javax.swing.JLabel();
        lblSubti = new javax.swing.JLabel();
        btnServidores = new javax.swing.JButton();
        btnSisArmaze = new javax.swing.JButton();
        btnDisRede = new javax.swing.JButton();
        btnAlimentacap = new javax.swing.JButton();
        btnControleAmbientais = new javax.swing.JButton();
        btnEnergia = new javax.swing.JButton();
        btnMnPrincipal = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTiTulo.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        lblTiTulo.setText("Calculo de Consumo de Energia Elétrica ");
        getContentPane().add(lblTiTulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 670, -1));

        lblSubti.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lblSubti.setText("Escolha o tipo de disoistivo a ser inserido");
        getContentPane().add(lblSubti, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 280, -1, -1));

        btnServidores.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnServidores.setText("Servidores");
        getContentPane().add(btnServidores, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 370, 260, -1));

        btnSisArmaze.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnSisArmaze.setText("Sistema de Armazenamento ");
        getContentPane().add(btnSisArmaze, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 410, -1, -1));

        btnDisRede.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnDisRede.setText("Dispositivo de Rede ");
        getContentPane().add(btnDisRede, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 450, 260, -1));

        btnAlimentacap.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnAlimentacap.setText("Alimentação");
        getContentPane().add(btnAlimentacap, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 490, 260, -1));

        btnControleAmbientais.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnControleAmbientais.setText("Controle Ambientais ");
        getContentPane().add(btnControleAmbientais, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 530, 260, -1));

        btnEnergia.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnEnergia.setText("Energias");
        getContentPane().add(btnEnergia, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 610, -1, -1));

        btnMnPrincipal.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnMnPrincipal.setText("Menu Principal");
        getContentPane().add(btnMnPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 610, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Imagens/fundo.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 750, 440));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Imagens/Consulta.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 1210, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EscolhaDispositivoEnEletrica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EscolhaDispositivoEnEletrica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EscolhaDispositivoEnEletrica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EscolhaDispositivoEnEletrica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EscolhaDispositivoEnEletrica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlimentacap;
    private javax.swing.JButton btnControleAmbientais;
    private javax.swing.JButton btnDisRede;
    private javax.swing.JButton btnEnergia;
    private javax.swing.JButton btnMnPrincipal;
    private javax.swing.JButton btnServidores;
    private javax.swing.JButton btnSisArmaze;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblSubti;
    private javax.swing.JLabel lblTiTulo;
    // End of variables declaration//GEN-END:variables
}
