/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.MenuPrincipalController;

/**
 *
 * @author davic
 */
public class MenuPrincipal extends javax.swing.JFrame {

    private final MenuPrincipalController controller;

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        this.controller = new MenuPrincipalController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTexto = new javax.swing.JLabel();
        lblFundo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnCadastro = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        mnOperação = new javax.swing.JMenu();
        mnRel = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTexto.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblTexto.setForeground(new java.awt.Color(255, 255, 255));
        lblTexto.setText("<html>\nEmergia e Fontes de Energia: Entendendo os Cálculos Energéticos<br><br>\n\nEmergia:<br><br>\nQuantidade total de energia, geralmente solar, usada para produzir bens, serviços ou processos. <br><br>\nEla considera toda a energia investida desde a origem até o resultado final, convertida em joules solares equivalentes (seJ).<br><br>\n\nEnergia elétrica: <br><br>\nForma versátil de energia obtida da conversão de fontes como água, vento ou calor. <br><br>\nTem alto valor emergético por envolver tecnologias complexas e infraestrutura.<br><br>\nEnergia de mão de obra:<br><br>\nRefere-se ao esforço físico e intelectual humano nos processos produtivos.<br><br>\nSeu valor pode ser estimado pela energia dos alimentos e dos recursos usados para sustentar o trabalhador.<br><br>\nEnergia térmica:<br><br>\nRelacionada ao calor, usada para aquecer ambientes, cozinhar ou realizar processos industriais. <br><br>\nA eficiência de uso influencia diretamente o investimento emergético necessário.<br><br>\n\nEenergia de combustíveis fósseis:<br><br>\nPetróleo, gás e carvão, é altamente concentrada e não renovável.<br><br>\nPossui custo emergético elevado, pois levou milhões de anos e muita energia solar para se formar.<br><br>\n\n\n</html>\n");
        getContentPane().add(lblTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 620));

        lblFundo.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Imagens/DataCenter Login2.jpg"))); // NOI18N
        lblFundo.setText("lblPlasn");
        getContentPane().add(lblFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1630, -1));

        mnCadastro.setText("Cadastro");
        mnCadastro.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jMenuItem1.setText("Empresa");
        mnCadastro.add(jMenuItem1);

        jMenuItem2.setText("Serviço");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        mnCadastro.add(jMenuItem2);

        jMenuBar1.add(mnCadastro);

        mnOperação.setText("Cálculo");
        mnOperação.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jMenuBar1.add(mnOperação);

        mnRel.setText("Relatório");
        jMenuBar1.add(mnRel);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        this.controller.navegarParaConsulta();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JLabel lblFundo;
    private javax.swing.JLabel lblTexto;
    private javax.swing.JMenu mnCadastro;
    private javax.swing.JMenu mnOperação;
    private javax.swing.JMenu mnRel;
    // End of variables declaration//GEN-END:variables
}
